[package]
name = "wasmer-usage"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
wasmer = { version = "3.1.1", features = ["compiler", "cranelift", "singlepass"] }
